server.document-root = "/var/www/html"
server.port = 8080
server.errorlog = "/dev/stderr"
server.breakagelog = "/dev/stderr"
server.modules += ("mod_cgi", "mod_rewrite")
cgi.assign = (".cgi" => "")
index-file.names = ("index.cgi")
url.rewrite-once = (
    "^/(?!index\\.cgi$).*" => "/index.cgi"
)
